-- DEPRECATED / SUPERSEDED
-- This file only ever added company_size + inquiry_type, which already existed
-- on contact_submissions. Running it is a no-op and does NOT add branching fields.
--
-- Use instead: supabase_contact_branch_migration.sql
-- That migration adds budget_range and all per-branch columns the /contact form needs.
